#!/usr/bin/env node
/**
 * Compile src/app.jsx → assets/app.js (no Babel-in-browser).
 * Usage: node scripts/build-app.mjs
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { transformAsync } from "@babel/core";
import { minify } from "terser";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcPath = join(root, "src", "app.jsx");
const outPath = join(root, "assets", "app.js");

const source = await readFile(srcPath, "utf8");
const transformed = await transformAsync(source, {
  filename: srcPath,
  presets: [["@babel/preset-react", { runtime: "classic" }]],
  babelrc: false,
  configFile: false,
  sourceMaps: false,
});

if (!transformed?.code) {
  throw new Error("Babel transform produced empty output");
}

const minified = await minify(transformed.code, {
  compress: {
    passes: 2,
    drop_console: false,
  },
  mangle: true,
  format: {
    comments: false,
    wrap_iife: false,
  },
});

if (!minified.code) {
  throw new Error("Terser minify produced empty output");
}

await mkdir(dirname(outPath), { recursive: true });
const banner = "/* auto-generated by scripts/build-app.mjs — edit src/app.jsx */\n";
await writeFile(outPath, banner + minified.code + "\n", "utf8");

const inKb = (Buffer.byteLength(source) / 1024).toFixed(1);
const outKb = (Buffer.byteLength(banner + minified.code) / 1024).toFixed(1);
console.log(`Built assets/app.js (${inKb} KB JSX → ${outKb} KB JS)`);
